#!/usr/bin/env bash

# entry script to launch the service

PROGRAM_PATH=/usr/local/pidash
VENV_PATH="$PROGRAM_PATH/venv_pidash"

source "$VENV_PATH/bin/activate"

export PROJECT_DIR="$PROGRAM_PATH"
export SRC_DIR="$PROGRAM_PATH/src"

cd "$PROGRAM_PATH"

python -u "src/pidash.py" "$@"

deactivate